### ISSUE TITLE
ipv6 address 'bug'

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#529]
When dialing an ipv6 address that starts with `fe08` fail to dial properly (not sure if this is a bug in Go or not). Ipfs will receive an address through the handshake that looks something like: `[fe80::42:acff:fe11:2c9]:4001`, attempt to dial it, and fail. This is what I beleive has been causing the sporadic failures on mars. We should filter out ipv6 addresses that match that pattern for now.

**Comment by cryptix** [comment]
> When dialing an ipv6 address that starts with fe08

I guess you mean `fe80` here, too?

This is not a bug regarding go, `fe80::/10` are [link-local addresses](https://en.wikipedia.org/wiki/IPv6_address#Local_addresses) and won't be routed (those are used for router solicitation broadcasts etc.) so you never can use those to connect across the internet.

Filtering those out when advertising to other clients definitely makes sense.




Small excursus: `fe80::` addresses are derived from the MAC addresses of the network interface. So you can make it up yourself.

Medium excursus: If you know the `fe80::` address of a device connected to the same switch, you need to tell your OS which network interface to use because it can't know through which to dial. Typically you append the interface name with a `%` like `ssh fe80::42:acff:fe11:2c9%re0`. Which fails horribly in browsers in case you hoped to reach the web-interface of your favourite NAS...

**Comment by whyrusleeping** [comment]
@cryptix thanks for the lesson! it was very appreciated. It sounds like we need to make sure not to advertise link local ipv6 addresses during our handshakes. 

@jbenet agree?

**Comment by jbenet** [comment]
@cryptix right!! 

@whyrusleeping Yep. We should add a `Multiaddr.IsIPLinkLocal()` like: https://github.com/jbenet/go-multiaddr-net/blob/master/ip.go#L9-L19

**Comment by whyrusleeping** [comment]
@jbenet did you push that change?

**Comment by jbenet** [comment]
no, sec i'll add it to fix/diag

**Comment by whyrusleeping** [comment]
:+1:

**Comment by jbenet** [comment]
ended up adding it to its own branch: https://github.com/jbenet/go-ipfs/pull/544

**Comment by whyrusleeping** [comment]
i believe this is closed now
