### ISSUE TITLE
`ipfs get` command

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#586]
the equivalent of `wget`. output to a path.

**Comment by mappum** [comment]
One thing that makes implementing this hard is that there isn't currently a way in the commands API to return multiple files in one response, or for the client to save the returned data to disk.

For now, it will be 100x less complex to make the daemon (instead of the client) save the output to disk. The downside is that this assumes the daemon is on the same machine as the client, but this should be true 99.9% of the time. Any objections to this?

**Comment by jbenet** [comment]
> commands API to return multiple files in one response

Just multiplex it? We're going to need a "stream of ipfs objects"

> it will be 100x less complex to make the daemon (instead of the client) save the output to disk. 

This wont work. we cannot assume the daemon is in the same machine. I'm already am using my cli to manage ipfs nodes in other machines.

**Comment by mappum** [comment]
Ok, we can use our own multiplexing scheme, but then HTTP clients won't be able to use the output of `get` unless they implement it, too. Everything else so far just uses existing standards, so that it's trivial to create API clients (the output of `cat` is just a normal HTTP file request, output of most commands are JSON, etc).

I was thinking we could bundle the files together as a tarball so that browsers could just download the output (we can even build a tarball from streams).

That's actually not the part that is hanging me up, but the part that deals with the API of the `commands` package. How does a run function return multiple files in a way that the client knows what to do with it? And where is the client logic of writing those demuxed files to disk going to happen? The commands API currently doesn't have a way to support this.

**Comment by jbenet** [comment]
> I was thinking we could bundle the files together as a tarball so that browsers could just download the output (we can even build a tarball from streams).

that would be really cool.

i dont think this is TRTTD, but the cmds api could test the provided reader matches a particular interface on writing out:

```go
// in http response part
if mfr, ok := r.(MultiFileReader); ok {
   r = tarballReader{mfr}
}

// in cli response part
if mfr, ok := r.(MultiFileReader); ok {
   // dont do anything. send it as is.
}

// in cli making request part (main), after running the command
if mfr, ok := r.(MultiFileReader); ok {
   // write these out to disk
}
```

It's also possible that the cmds lib could have a function to operate on the client side. like Run, but on the client's side so you can do things with return values (like write out to disk at a particular path)

**Comment by whyrusleeping** [comment]
the tar idea would be pretty easy IMO: http://golang.org/pkg/archive/tar

**Comment by whyrusleeping** [comment]
would also be neat to have an option to wrap the tar writer in a gzip writer for using the cli to access remote machines
